// <auto-generated />
using System;
using AgroShield.AlertEngine.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroShield.AlertEngine.Api.Migrations
{
    [DbContext(typeof(AgroShieldDbContext))]
    partial class AgroShieldDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AgroShield.AlertEngine.Api.Entities.HistoricoAlerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AcaoRecomendada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DiasSemImagemSatelite")
                        .HasColumnType("int");

                    b.Property<string>("MensagemParaFala")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MensagemTecnica")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal?>("NdviMedio")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NdviZonaNorte")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("NdviZonaSul")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TerrenoId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("UmidadeRelativa")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("TerrenoId");

                    b.ToTable("historico_alertas");
                });

            modelBuilder.Entity("AgroShield.AlertEngine.Api.Entities.Terreno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AreaCultivoHectares")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AreaReservaHectares")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AreaTotalHectares")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CulturaAtual")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EmCultivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IrrigacaoAtiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TipoSolo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("terrenos");
                });

            modelBuilder.Entity("AgroShield.AlertEngine.Api.Entities.HistoricoAlerta", b =>
                {
                    b.HasOne("AgroShield.AlertEngine.Api.Entities.Terreno", "Terreno")
                        .WithMany("HistoricoAlertas")
                        .HasForeignKey("TerrenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terreno");
                });

            modelBuilder.Entity("AgroShield.AlertEngine.Api.Entities.Terreno", b =>
                {
                    b.Navigation("HistoricoAlertas");
                });
#pragma warning restore 612, 618
        }
    }
}
